# Generated by Django 5.0 on 2023-12-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('bookings', models.IntegerField()),
            ],
        ),
    ]
