# Generated by Django 5.0 on 2023-12-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=100)),
                ('book_time', models.TimeField()),
                ('user', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('nos', models.IntegerField()),
            ],
        ),
    ]
