# Generated by Django 4.2.7 on 2023-11-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=100)),
                ('doj', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('mobileNo', models.CharField(max_length=100)),
                ('problem', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
