# Generated by Django 4.2.7 on 2023-11-16 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='collge',
            new_name='college',
        ),
    ]
